#pragma once

// ============================================================
// Blind Flight — Splash Screen (Session 8)
// ============================================================
// Animated startup screen:
//   1. Paper plane flies along the logo's dotted flight path
//   2. Dotted trail draws behind the plane
//   3. Logo text fades in
//   4. Holds on full logo until user input
//
// Uses pre-converted RGB565 image data (img_*.h) and the
// waypoint table (flight_path.h) generated by convert_assets.py.
// ============================================================

#include "ui.h"

// The splash screen instance — push this at startup
extern const Screen screenSplash;

// Run the startup animation (blocking).
// Called from screenSplash's onEnter. Can also be called
// standalone if you want to replay the animation.
void splashRunAnimation();
